# -*- mode: ruby -*-
# vi: set ft=ruby :

def populate_pub_key(config)
 config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end

Vagrant.configure("2") do |config|
  os = "centos/7"
  subnet = "172.16.10"

  config.vm.define "master", primary: true do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
      vb.name = "master"
    end
    master.vm.box = "#{os}"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "#{subnet}.10"
    populate_pub_key(master)
  end

  [["node1", "#{subnet}.11"], ["node2", "#{subnet}.12"]].each do |vmname,ip|
    config.vm.define "#{vmname}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
        vb.name = "#{vmname}"
      end
      node.vm.box = "#{os}"
      node.vm.hostname = "#{vmname}"
      node.vm.network "private_network", ip: "#{ip}"
      populate_pub_key(node)
    end
  end
end
